[browser]
gatherUsageStats = false

[server]
headless = true
address = "0.0.0.0"
port = 8501

[theme]
primaryColor = "#005293"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[client]
showErrorDetails = true